# Generated by Django 5.0.6 on 2024-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
